### ISSUE TITLE
Cannot add authenticate

### ISSUE THREAD

**Issue by Xeroner** [Jessecar96/SteamBot#878]
Hi there, i can't add phone number.
Ive got numer added to my steam account...

exec 0 linkauth
[(System) 2015-12-11 21:41:41] DEBUG: Sending command "linkauth" to Bot at index 0
botmgr > [CSBOX.PL 2015-12-11 21:41:43] INTERFACE: Enter Steam Guard code from email (type "input [index] [code]"):
input 0 Y5KD2
[(System) 2015-12-11 21:42:04] DEBUG: Sending input "Y5KD2" to Bot at index 0
botmgr > [CSBOX.PL 2015-12-11 21:42:06] INTERFACE: Enter phone number with country code, e.g. +1XXXXXXXXXXX (type "input [index] [number]"):
input 0 +48xxxxxxx
[(System) 2015-12-11 21:42:18] DEBUG: Sending input "+48xxxxxxx" to Bot at index 0
botmgr > [CSBOX.PL 2015-12-11 21:42:19] ERROR: Error adding authenticator: GeneralFailure

Help please

**Comment by scholtzm** [comment]
Did you just paste your private phone number in here?

**Comment by Xeroner** [comment]
Updated, want to help? :)

**Comment by waylaidwanderer** [comment]
Lol I can still see it from my email.

**Comment by deadbeat91** [comment]
string response = SteamWeb.MobileLoginRequest(APIEndpoints.COMMUNITY_BASE + "/steamguard/phoneajax", "GET", postData, _cookies);

Returns: {\"success\":false,\"error_text\":\"Missing or invalid form session key\",\"fatal\":false}

**Comment by Jessecar96** [comment]
This was fixed in the latest SteamAuth commit

**Comment by deadbeat91** [comment]
Cool Cool, will download latest git :+1:

**Comment by Xeroner** [comment]
It's not fixed!, it's not working at all, still got this same problem.

**Comment by speed-str** [comment]
I don't think its fixed, still having the same issue with the newest git
Log--
[#1 2015-12-21 23:26:59] INFO: Connecting...
[#1 2015-12-21 23:26:59] SUCCESS: Done Loading Bot!
[#1 2015-12-21 23:27:05] SUCCESS: User Authenticated!
[#1 2015-12-21 23:27:06] INFO: Downloading Schema...
[#1 2015-12-21 23:27:24] SUCCESS: Schema Downloaded!
[#1 2015-12-21 23:27:24] SUCCESS: Steam Bot Logged In Completely!
[#1 2015-12-21 23:27:53] INTERFACE: Enter Steam Guard code from email (type "input [index] [code]"):
[#1 2015-12-21 23:28:07] INFO: Linking mobile authenticator...
[#1 2015-12-21 23:28:08] INTERFACE: Enter phone number with country code, e.g. +1XXXXXXXXXXX (type "input [index] [number]"):
[#1 2015-12-21 23:28:43] ERROR: Error adding authenticator: GeneralFailure

P.S removed all the mobile number associated to the account. still no luck
