### ISSUE TITLE
NewtonSoft.Json crash

### ISSUE THREAD

**Issue by lexor** [Jessecar96/SteamBot#924]
NewtonSoft.Json crashed yesterday please help guys
https://i.gyazo.com/230cf59d6c4d22dba197f56ea3d29728.png
https://i.gyazo.com/b48d3e88cafe207e6db59b92734a64a5.png

**Comment by BlueRaja** [comment]
This should be fixed by #913 

I'm still waiting on anyone to verify that this PR works so we can get it merged.

**Comment by lexor** [comment]
https://i.gyazo.com/a39fac31fb0e1928555e442e1e63bdc8.png
https://i.gyazo.com/b05e758b567c0ee0c1ee3a93c3b3d2d7.png
Problem not fixed pls help bro

**Comment by BlueRaja** [comment]
Those screenshots clearly indicate you didn't merge the PR into your own repo.  See https://github.com/Jessecar96/SteamBot/issues/919#issuecomment-179528263

**Comment by lexor** [comment]
I cant PR because no have permissions.

**Comment by BlueRaja** [comment]
I think I'm going to have to close this with #427 #527, this is an API meant for developers, not a pre-built bot.  Sorry.
